pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

includeBuild('../UFO-Core-1.21.1') {
    dependencySubstitution {
        substitute module('com.raishxn.ufocore:raishxcore') using project(':')
    }
}
