package com.raishxn.ufo.datagen;

import appeng.core.definitions.AEBlocks;
import appeng.core.definitions.AEItems;
import com.raishxn.ufo.fluid.ModFluids;
import com.raishxn.ufo.item.ModItems;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.recipes.RecipeOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.conditions.ModLoadedCondition;

import java.util.List;

/** Original focused simulations with amplified outputs, plus one MK3 omnibus program. */
public final class StellarSimulationCatalog {
    private StellarSimulationCatalog() { }

    public static void build(RecipeOutput c) {
        List<StellarSimulationRecipeBuilder> programs = new java.util.ArrayList<>();
        program(programs, "stellar_simulation/massive_iron_synthesis")
                .simulationName("Massive Iron Synthesis")
                .output(Items.IRON_INGOT, 15000000)
                .output(Items.REDSTONE, 8000000)
                .output(Items.QUARTZ, 6000000)
                .output(Items.COBBLESTONE, 30000000)
                .output(Items.OBSIDIAN, 4000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 2000000)
                .outputFluid(ModFluids.SOURCE_UU_AMPLIFIER_FLUID.get(), 1500000)
                .outputFluid(ModFluids.SOURCE_STABLE_COOLANT.get(), 750000)
                .outputFluid(ModFluids.SOURCE_WHITE_DWARF_FRAGMENT_FLUID.get(), 500000)
                .inputItem(ModItems.ENRICHED_NEUTRONIUM_SPHERE.get(), 160)
                .inputItem(ModItems.OBSIDIAN_MATRIX.get(), 1024)
                .inputItem(AEItems.MATTER_BALL.get(), 32768)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 8000000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 2000000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 150000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 100000)
                .fieldLevel(3)
                .energy(3000000000L)
                .time(4800)
                .save(c);

        program(programs, "stellar_simulation/massive_copper_synthesis")
                .simulationName("Massive Copper Synthesis")
                .output(Items.COPPER_INGOT, 15000000)
                .output(Items.REDSTONE, 5000000)
                .output(Items.AMETHYST_SHARD, 3500000)
                .output(Items.GLOWSTONE_DUST, 4500000)
                .output(Items.QUARTZ, 5000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 1750000)
                .outputFluid(ModFluids.SOURCE_UU_AMPLIFIER_FLUID.get(), 1250000)
                .outputFluid(ModFluids.SOURCE_STABLE_COOLANT.get(), 600000)
                .outputFluid(ModFluids.SOURCE_PULSAR_FRAGMENT_FLUID.get(), 450000)
                .inputItem(ModItems.ENRICHED_NEUTRONIUM_SPHERE.get(), 160)
                .inputItem(ModItems.OBSIDIAN_MATRIX.get(), 768)
                .inputItem(AEItems.MATTER_BALL.get(), 24576)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 7800000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 1600000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 140000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 100000)
                .fieldLevel(3)
                .energy(3200000000L)
                .time(4800)
                .save(c);

        program(programs, "stellar_simulation/massive_gold_synthesis")
                .simulationName("Massive Gold Synthesis")
                .output(Items.GOLD_INGOT, 15000000)
                .output(Items.DIAMOND, 1500000)
                .output(Items.EMERALD, 1500000)
                .output(Items.LAPIS_LAZULI, 9000000)
                .output(Items.GLOWSTONE_DUST, 7000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 2500000)
                .outputFluid(ModFluids.SOURCE_SPATIAL_FLUID.get(), 900000)
                .outputFluid(ModFluids.SOURCE_STABLE_COOLANT.get(), 900000)
                .outputFluid(ModFluids.SOURCE_NEUTRON_STAR_FRAGMENT_FLUID.get(), 600000)
                .inputItem(ModItems.ENRICHED_NEUTRONIUM_SPHERE.get(), 220)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 64)
                .inputItem(AEItems.MATTER_BALL.get(), 32768)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 9500000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 2500000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 220000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 150000)
                .fieldLevel(3)
                .energy(4200000000L)
                .time(4800)
                .save(c);

        program(programs, "stellar_simulation/massive_netherite_synthesis")
                .simulationName("Massive Netherite Synthesis")
                .output(Items.NETHERITE_INGOT, 5000000)
                .output(Items.NETHERITE_SCRAP, 12000000)
                .output(Items.GOLD_INGOT, 9000000)
                .output(Items.QUARTZ, 10000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 3000000)
                .outputFluid(ModFluids.SOURCE_TEMPORAL_FLUID.get(), 1200000)
                .outputFluid(ModFluids.SOURCE_SPATIAL_FLUID.get(), 1000000)
                .outputFluid(ModFluids.SOURCE_PRIMORDIAL_MATTER_FLUID.get(), 800000)
                .inputItem(ModItems.ENRICHED_NEUTRONIUM_SPHERE.get(), 320)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 128)
                .inputItem(ModItems.DARK_MATTER.get(), 64)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 14000000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 4000000)
                .inputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 1500000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 320000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 250000)
                .fieldLevel(3)
                .energy(6500000000L)
                .time(4800)
                .save(c);

        program(programs, "stellar_simulation/stellar_synthesis")
                .simulationName("Stellar Synthesis")
                .output(ModItems.PULSAR_FRAGMENT_DUST.get(), 12000000)
                .output(ModItems.WHITE_DWARF_MATTER.get(), 7000000)
                .output(ModItems.NEUTRON_STAR_MATTER.get(), 5000000)
                .output(ModItems.PULSAR_MATTER.get(), 3500000)
                .output(ModItems.QUANTUM_ANOMALY.get(), 500000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 1000000)
                .outputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 600000)
                .outputFluid(ModFluids.SOURCE_PRIMORDIAL_MATTER_FLUID.get(), 300000)
                .outputFluid(ModFluids.SOURCE_TEMPORAL_FLUID.get(), 250000)
                .inputItem(ModItems.CHARGED_ENRICHED_NEUTRONIUM_SPHERE.get(), 64)
                .inputItem(ModItems.AETHER_CONTAINMENT_CAPSULE.get(), 32)
                .inputItem(ModItems.DARK_MATTER.get(), 16)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 64)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 2500000)
                .inputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 1000000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 500000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 180000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 220000)
                .fieldLevel(3)
                .energy(2500000000L)
                .time(4800)
                .save(c);

        program(programs, "stellar_simulation/advancedae_quantum")
                .simulationName("Quantum Alloy Infusion")
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("advanced_ae:quantum_alloy")), 18000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("advanced_ae:printed_quantum_processor")), 12000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("advanced_ae:quantum_processor")), 6000000)
                .output(AEItems.SINGULARITY, 1500000)
                .output(ModItems.DIMENSIONAL_PROCESSOR.get(), 3000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 2500000)
                .outputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 1500000)
                .outputFluid(ModFluids.SOURCE_SPATIAL_FLUID.get(), 750000)
                .outputFluid(ModFluids.SOURCE_TEMPORAL_FLUID.get(), 750000)
                .inputItem(BuiltInRegistries.ITEM.get(ResourceLocation.parse("advanced_ae:quantum_infused_dust")), 4096)
                .inputItem(ModItems.DIMENSIONAL_PROCESSOR.get(), 1024)
                .inputItem(ModItems.OBSIDIAN_MATRIX.get(), 512)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 4500000)
                .inputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 2500000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 450000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 600000)
                .fieldLevel(3)
                .energy(2400000000L)
                .time(4800)
                .save(c.withConditions(new ModLoadedCondition("advanced_ae")));

        program(programs, "stellar_simulation/ae2_singularity")
                .simulationName("Quantum Singularity Collapse")
                .output(AEItems.SINGULARITY, 15000000)
                .output(AEItems.MATTER_BALL.get(), 24000000)
                .output(AEItems.SKY_DUST, 32000000)
                .output(AEItems.CERTUS_QUARTZ_CRYSTAL, 24000000)
                .output(AEItems.FLUIX_CRYSTAL, 18000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 2500000)
                .outputFluid(ModFluids.SOURCE_UU_AMPLIFIER_FLUID.get(), 3000000)
                .outputFluid(ModFluids.SOURCE_SPATIAL_FLUID.get(), 1000000)
                .outputFluid(ModFluids.SOURCE_STABLE_COOLANT.get(), 1000000)
                .inputItem(AEItems.MATTER_BALL.get(), 65536)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 256)
                .inputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 4000000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 2000000)
                .fuel(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 350000)
                .coolant(ModFluids.SOURCE_STABLE_COOLANT.get(), 500000)
                .coolingLevel(2)
                .fieldLevel(3)
                .energy(2100000000L)
                .time(4800)
                .save(c.withConditions(new ModLoadedCondition("ae2")));

        program(programs, "stellar_simulation/extendedae_entro")
                .simulationName("Entro Crystal Synthesis")
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("extendedae:entro_crystal")), 18000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("extendedae:concurrent_processor_print")), 15000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("extendedae:concurrent_processor")), 7500000)
                .output(AEItems.SINGULARITY, 1500000)
                .output(ModItems.QUANTUM_ANOMALY.get(), 750000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 3000000)
                .outputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 2000000)
                .outputFluid(ModFluids.SOURCE_SPATIAL_FLUID.get(), 1200000)
                .outputFluid(ModFluids.SOURCE_TEMPORAL_FLUID.get(), 1200000)
                .inputItem(BuiltInRegistries.ITEM.get(ResourceLocation.parse("extendedae:entro_dust")), 4096)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 512)
                .inputItem(ModItems.DIMENSIONAL_PROCESSOR.get(), 1024)
                .inputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 3200000)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 5000000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 650000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 850000)
                .fieldLevel(3)
                .energy(3200000000L)
                .time(4800)
                .save(c.withConditions(new ModLoadedCondition("extendedae")));

        program(programs, "stellar_simulation/megacells_skysteel")
                .simulationName("Sky Steel Forging")
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("megacells:sky_steel_block")), 15000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("megacells:printed_accumulation_processor")), 12000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("megacells:accumulation_processor")), 6000000)
                .output(AEItems.SKY_DUST, 20000000)
                .output(Items.IRON_INGOT, 18000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 1500000)
                .outputFluid(ModFluids.SOURCE_WHITE_DWARF_FRAGMENT_FLUID.get(), 1000000)
                .outputFluid(ModFluids.SOURCE_STABLE_COOLANT.get(), 600000)
                .outputFluid(ModFluids.SOURCE_UU_AMPLIFIER_FLUID.get(), 750000)
                .inputItem(AEBlocks.SKY_STONE_BLOCK, 8192)
                .inputItem(Items.IRON_BLOCK, 4096)
                .inputItem(ModItems.OBSIDIAN_MATRIX.get(), 256)
                .inputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 2000000)
                .fuel(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 250000)
                .coolant(ModFluids.SOURCE_GELID_CRYOTHEUM.get(), 500000)
                .coolingLevel(2)
                .fieldLevel(2)
                .energy(1200000000L)
                .time(3600)
                .save(c.withConditions(new ModLoadedCondition("megacells")));

        program(programs, "stellar_simulation/mekanism_ethylene")
                .simulationName("Ethylene Enrichment")
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:hdpe_sheet")), 15000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:hdpe_pellet")), 45000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:substrate")), 30000000)
                .output(ModItems.DUST_BLIZZ.get(), 6000000)
                .output(ModItems.DUST_CRYOTHEUM.get(), 3000000)
                .outputFluid(ModFluids.SOURCE_GELID_CRYOTHEUM.get(), 1200000)
                .outputFluid(ModFluids.SOURCE_STABLE_COOLANT.get(), 1000000)
                .outputFluid(ModFluids.SOURCE_UU_AMPLIFIER_FLUID.get(), 900000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 750000)
                .inputItem(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:substrate")), 4096)
                .inputItem(ModItems.OBSIDIAN_MATRIX.get(), 256)
                .inputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 800000)
                .fuel("mekanism:ethene", 1500000)
                .coolant(ModFluids.SOURCE_GELID_CRYOTHEUM.get(), 2000000)
                .coolingLevel(2)
                .fieldLevel(2)
                .energy(900000000L)
                .time(3600)
                .save(c.withConditions(new ModLoadedCondition("mekanism")));

        program(programs, "stellar_simulation/mekanism_fission")
                .simulationName("Fission Reactor Process")
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:pellet_antimatter")), 2500000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:pellet_polonium")), 18000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:pellet_plutonium")), 15000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:hdpe_sheet")), 6000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:substrate")), 8000000)
                .outputFluid(ModFluids.SOURCE_TEMPORAL_FLUID.get(), 1800000)
                .outputFluid(ModFluids.SOURCE_STABLE_COOLANT.get(), 1500000)
                .outputFluid(ModFluids.SOURCE_SPATIAL_FLUID.get(), 1200000)
                .outputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 1000000)
                .inputItem(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:pellet_plutonium")), 2048)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 512)
                .inputFluid(BuiltInRegistries.FLUID.get(ResourceLocation.parse("mekanism:sulfuric_acid")), 1200000)
                .fuel("mekanism:sulfuric_acid", 2400000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 3000000)
                .fieldLevel(3)
                .energy(3400000000L)
                .time(4800)
                .save(c.withConditions(new ModLoadedCondition("mekanism")));

        program(programs, "stellar_simulation/mekanism_metallurgic_surge")
                .simulationName("Mekanism Metallurgic Surge")
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_lead")), 18000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_tin")), 18000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_osmium")), 18000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_uranium")), 15000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_refined_glowstone")), 12000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_refined_obsidian")), 12000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_steel")), 24000000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("mekanism:ingot_bronze")), 24000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 2500000)
                .outputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 2000000)
                .outputFluid(ModFluids.SOURCE_NEUTRON_STAR_FRAGMENT_FLUID.get(), 1000000)
                .outputFluid(ModFluids.SOURCE_WHITE_DWARF_FRAGMENT_FLUID.get(), 1000000)
                .inputItem(ModItems.ENRICHED_NEUTRONIUM_SPHERE.get(), 256)
                .inputItem(ModItems.DIMENSIONAL_PROCESSOR.get(), 2048)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 512)
                .inputItem(AEItems.MATTER_BALL.get(), 65536)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 10000000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 4000000)
                .inputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 2000000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 450000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 350000)
                .fieldLevel(3)
                .energy(3800000000L)
                .time(4800)
                .save(c.withConditions(new ModLoadedCondition("mekanism")));

        program(programs, "stellar_simulation/vanilla_reagent_fabrication")
                .simulationName("Vanilla Reagent Fabrication")
                .output(Items.GHAST_TEAR, 15000000)
                .output(Items.MAGMA_CREAM, 18000000)
                .output(Items.SUGAR, 24000000)
                .output(Items.GUNPOWDER, 24000000)
                .output(Items.GLOWSTONE_DUST, 30000000)
                .output(Items.REDSTONE, 30000000)
                .output(Items.NETHER_STAR, 1500000)
                .output(Items.SLIME_BALL, 20000000)
                .outputFluid(ModFluids.SOURCE_LIQUID_STARLIGHT_FLUID.get(), 2000000)
                .outputFluid(ModFluids.SOURCE_UU_AMPLIFIER_FLUID.get(), 1750000)
                .outputFluid(ModFluids.SOURCE_SPATIAL_FLUID.get(), 1250000)
                .outputFluid(ModFluids.SOURCE_TEMPORAL_FLUID.get(), 1250000)
                .inputItem(ModItems.ENRICHED_NEUTRONIUM_SPHERE.get(), 128)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 384)
                .inputItem(AEItems.MATTER_BALL.get(), 49152)
                .inputItem(ModItems.OBSIDIAN_MATRIX.get(), 768)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 7000000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 3000000)
                .inputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 1500000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 320000)
                .coolant(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 300000)
                .fieldLevel(3)
                .energy(3000000000L)
                .time(4800)
                .save(c);

        buildOmnibus(c, programs);
    }
    private static StellarSimulationRecipeBuilder program(List<StellarSimulationRecipeBuilder> programs, String name) {
        var builder = StellarSimulationRecipeBuilder.create(name).outputMultipliers(10, 50);
        programs.add(builder);
        return builder;
    }

    private static void buildOmnibus(RecipeOutput recipes, List<StellarSimulationRecipeBuilder> programs) {
        StellarSimulationRecipeBuilder.create("stellar_simulation/stellar_omnibus")
                .simulationName("Stellar Omnibus")
                .mergeOutputsFrom(programs)
                .removeOutput(Items.COBBLESTONE)
                .removeOutput(Items.OBSIDIAN)
                .output(ModItems.WHITE_DWARF_FRAGMENT_INGOT.get(), 30_000_000)
                .output(ModItems.NEUTRON_STAR_FRAGMENT_INGOT.get(), 25_000_000)
                .output(ModItems.PULSAR_FRAGMENT_INGOT.get(), 20_000_000)
                .output(ModItems.OBSIDIAN_MATRIX.get(), 25_000_000)
                .output(ModItems.CHARGED_ENRICHED_NEUTRONIUM_SPHERE.get(), 10_000_000)
                .output(ModItems.UU_MATTER_CRYSTAL.get(), 30_000_000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("appflux:harden_insulating_resin")), 40_000_000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("appflux:charged_redstone")), 40_000_000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("advanced_ae:quantum_infused_dust")), 30_000_000)
                .output(BuiltInRegistries.ITEM.get(ResourceLocation.parse("advanced_ae:shattered_singularity")), 15_000_000)
                .outputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 50_000_000)
                .outputFluid(ModFluids.SOURCE_BOSE_EINSTEIN_CONDENSATE.get(), 50_000_000)
                .outputFluid(BuiltInRegistries.FLUID.get(ResourceLocation.parse("mekanismgenerators:deuterium")), 50_000_000)
                .outputFluid(BuiltInRegistries.FLUID.get(ResourceLocation.parse("mekanismgenerators:tritium")), 50_000_000)
                .outputFluid(BuiltInRegistries.FLUID.get(ResourceLocation.parse("mekanismgenerators:fusion_fuel")), 50_000_000)
                .inputItem(ModItems.CHARGED_ENRICHED_NEUTRONIUM_SPHERE.get(), 1024)
                .inputItem(ModItems.QUANTUM_ANOMALY.get(), 4096)
                .inputItem(ModItems.DIMENSIONAL_PROCESSOR.get(), 4096)
                .inputItem(AEItems.MATTER_BALL.get(), 262144)
                .inputFluid(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 40_000_000)
                .inputFluid(ModFluids.SOURCE_TRANSCENDING_MATTER_FLUID.get(), 12_000_000)
                .inputFluid(ModFluids.SOURCE_UU_MATTER_FLUID.get(), 10_000_000)
                .fuel(ModFluids.SOURCE_RAW_STAR_MATTER_PLASMA_FLUID.get(), 2_000_000)
                .coolant(4_000_000).fieldLevel(3).energy(20_000_000_000L).time(4800)
                .save(recipes.withConditions(
                        new ModLoadedCondition("advanced_ae"),
                        new ModLoadedCondition("extendedae"),
                        new ModLoadedCondition("megacells"),
                        new ModLoadedCondition("mekanism"),
                        new ModLoadedCondition("mekanismgenerators"),
                        new ModLoadedCondition("appflux")));
    }
}
