modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"
[[mods]]
modId="ufo_tests"
version="1"
displayName="UFO development tests"
[[dependencies.ufo_tests]]
modId="ufo"
type="required"
versionRange="[3.0.0-beta.1,)"
ordering="AFTER"
side="BOTH"
